<?php

        $a=array(
            [
              'idPedido'=> random_int(0,100),
              'idRequest'=>"2",
              'quantity'=>0,
              'total'=>0.0,
              'name' =>'Roberto scamilla',
              'address' =>'zóna 12',
              'wayToPay'=>"Tarjeta",
              'createdAt'=>"27/01/2021",
              'requestId'=>"1",
              'comments'=>"tarjeta visa",
              'additionalShops'=>"",
              'vuelto'=>"",
              'recipe'=>"",
              'insuranceId'=>0,
              'nit'=>"",
              'cliId'=>"",
              'char1'=>"",
              'estado'=>5,
            ],
            [
                'idPedido'=> random_int(101,200),
                'idRequest'=>"3",
                'quantity'=>0,
                'total'=>0.0,
                'name' =>'Roberto scamilla',
                'address' =>'zóna 12',
                'wayToPay'=>"Tarjeta",
                'createdAt'=>"27/01/2021",
                'requestId'=>"1",
                'comments'=>"tarjeta visa",
                'additionalShops'=>"",
                'vuelto'=>"",
                'recipe'=>"",
                'insuranceId'=>0,
                'nit'=>"",
                'cliId'=>"",
                'char1'=>"",
                'estado'=>5,
            ],
            [
                'idPedido'=> random_int(201,300),
                'idRequest'=>"4",
                'quantity'=>0,
                'total'=>0.0,
                'name' =>'Roberto scamilla',
                'address' =>'zóna 12',
                'wayToPay'=>"Tarjeta",
                'createdAt'=>"27/01/2021",
                'requestId'=>"1",
                'comments'=>"tarjeta visa",
                'additionalShops'=>"",
                'vuelto'=>"",
                'recipe'=>"",
                'insuranceId'=>0,
                'nit'=>"",
                'cliId'=>"",
                'char1'=>"",
                'estado'=>5,
            ],
            [
                'idPedido'=> random_int(301,400),
                'idRequest'=>"5",
                'quantity'=>0,
                'total'=>0.0,
                'name' =>'Roberto scamilla',
                'address' =>'zóna 12',
                'wayToPay'=>"Tarjeta",
                'createdAt'=>"27/01/2021",
                'requestId'=>"1",
                'comments'=>"tarjeta visa",
                'additionalShops'=>"",
                'vuelto'=>"",
                'recipe'=>"",
                'insuranceId'=>0,
                'nit'=>"",
                'cliId'=>"",
                'char1'=>"",
                'estado'=>5,
            ],
            [
                'idPedido'=> random_int(401,500),
                'idRequest'=>"6",
                'quantity'=>0,
                'total'=>0.0,
                'name' =>'Roberto scamilla',
                'address' =>'zóna 12',
                'wayToPay'=>"Tarjeta",
                'createdAt'=>"27/01/2021",
                'requestId'=>"1",
                'comments'=>"tarjeta visa",
                'additionalShops'=>"",
                'vuelto'=>"",
                'recipe'=>"",
                'insuranceId'=>0,
                'nit'=>"",
                'cliId'=>"",
                'char1'=>"",
                'estado'=>5,
            ],

        );
    echo json_encode($a);
?>
